// WARNING! This file is generated by a tool.
// It exists only to allow PO editors to get translation keys from source code.
_' + tag + ')
_' + type + ')
_')[0] + ')
_i("Read in ${locale}")
_i('fr')
_('Language')