on:
  pull_request:
    types: [opened]
  issue_comment:
    types: [created]

jobs:
  approve:
    name: Approve Backstop changes
    if: ${{ github.repository_owner == 'inclusive-design'}}
    runs-on: ubuntu-latest
    steps:
      - uses: khan/pull-request-comment-trigger@master
        id: approve
        with:
          trigger: '#backstop/approve'
          reaction: +1
        env:
          GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
      - uses: actions/checkout@v2
        if: steps.approve.outputs.triggered == 'true'
      - uses: actions/setup-node@v1.4.3
        if: steps.approve.outputs.triggered == 'true'
        with:
          node-version: '12'
      - name: Cache node modules
        if: steps.approve.outputs.triggered == 'true'
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
      - name: Wait for Netlify deploy preview
        if: steps.approve.outputs.triggered == 'true'
        uses: jakepartusch/wait-for-netlify-action@v1
        id: netlify
        with:
          site_name: 'idrc'
      - name: Set environment variables
        if: steps.approve.outputs.triggered == 'true'
        uses: allenevans/set-env@v1.1.0
        with:
          BASE_URL: ${{ steps.netlify.outputs.url }}
      - name: Install dependencies, run and approve visual regression tests
        if: steps.approve.outputs.triggered == 'true'
        run: |
          npm i
          npm i -g backstopjs
          npm run test:backstop
          npm run backstop:approve
        env:
          CI: true
      - name: Commit updated reference files
        if: steps.approve.outputs.triggered == 'true'
        uses: stefanzweifel/git-auto-commit-action@v4.1.1
        with:
          commit_message: 'ci: update Backstop reference images'
